import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSideBar";
import QueryProvider from "@/providers/query-provider";
import { Header } from "@/components/Header";
import { Toaster } from "sonner";
import { ChatWidget } from "@/components/ChatWidget";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VIETNAPIG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <QueryProvider>
          {/* <SidebarProvider>
            <AppSidebar />
            <SidebarInset>

              <Header /> */}
              <main >{children}</main>
              <Toaster />
              {/* <ChatWidget />
            </SidebarInset>
          </SidebarProvider> */}
        </QueryProvider>
      </body>
    </html>
  );
}
