import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSideBar";
import QueryProvider from "@/providers/query-provider";
import { Header } from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <div className="flex flex-col">
          <SidebarProvider>
          <AppSidebar />
            <SidebarTrigger />
            <div className="min-h-screen w-full">
            <Header/>
            <main className="min-h-screen w-full p-4">
              {children}
            </main>
            </div>
        </SidebarProvider>
          </div>
          
        </QueryProvider>
         
      </body>
    </html>
  );
}
